export const FETCH_MEMO_LIST = 'FETCH_MEMO_LIST';
export const FETCH_MEMO_LIST_SUCCEEDED = 'FETCH_MEMO_LIST_SUCCEEDED';
export const FETCH_MEMO_LIST_FAILED = 'FETCH_MEMO_LIST_FAILED';

export const FETCH_MEMO = 'FETCH_MEMO';